# Generated by Django 6.0.1 on 2026-03-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Giới thiệu cửa hàng'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='store',
            name='zalo_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Số Zalo'),
        ),
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=200, verbose_name='Tên điện thoại')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá tham khảo (VNĐ)')),
                ('stock_status', models.CharField(choices=[('in_stock', 'Còn hàng'), ('low_stock', 'Sắp hết hàng'), ('out_of_stock', 'Hết hàng')], default='in_stock', max_length=20, verbose_name='Tình trạng còn hàng')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='stores.store')),
            ],
        ),
    ]
