# Generated by Django 6.0.1 on 2026-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_description_store_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
