# Generated by Django 6.0.1 on 2026-03-25 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_phoneproduct_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Cửa hàng', 'verbose_name_plural': 'Cửa hàng'},
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh upload'),
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='specs',
            field=models.TextField(blank=True, default='', verbose_name='Thông số kỹ thuật'),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh URL'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'Còn hàng'), ('low_stock', 'Sắp hết hàng'), ('out_of_stock', 'Hết hàng')], default='in_stock', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='stores.store', verbose_name='Cửa hàng'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(verbose_name='Vĩ độ'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(verbose_name='Kinh độ'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên cửa hàng'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo')], default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.phoneproduct', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn',
                'verbose_name_plural': 'Sản phẩm trong đơn',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.phoneproduct', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giỏ',
                'verbose_name_plural': 'Sản phẩm trong giỏ',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
